app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

use App\Models\Contacts;

Route::group([
	'prefix' => 'admin',
	'namespace' => 'Admin',
	'middleware' => ['auth', 'roles'],
	'roles' => ['administrator', 'manager'],
], function () {
	# Admin users
	Route::resource('users', 'UserController');
	Route::resource('settings', 'SettingController');
	# Admin bars
	Route::get('/faqs/{id}/switchActive', ['uses' => 'FaqController@switchActive', 'as' => 'admin.faqs.switchActive']);
	Route::resource('faqs', 'FaqController');
	Route::get('/reqs/statistic', ['uses' => 'ReqController@statistic', 'as' => 'admin.reqs.statistic']);
	Route::get('/reqs/change_month', ['uses' => 'ReqController@change_month', 'as' => 'admin.reqs.change_month']);
	Route::get('/reqs/excel', ['uses' => 'ReqController@excel', 'as' => 'admin.reqs.excel']);
	Route::get('/reqs/search', ['uses' => 'ReqController@search', 'as' => 'admin.reqs.search']);
	Route::get('/reqs/switch_status/{id}/{status}', ['uses' => 'ReqController@switch_status', 'as' => 'admin.reqs.switch_status']);
	Route::post('/reqs/load_file/{id}', ['uses' => 'ReqController@load_file', 'as' => 'admin.reqs.load_file']);
	Route::get('/reqs/{id}/first', ['uses' => 'ReqController@first', 'as' => 'admin.reqs.first']);
	Route::get('/reqs/{id}/update_watch', ['uses' => 'ReqController@update_watch', 'as' => 'admin.reqs.update_watch']);
	Route::get('/contacts/offer', ['uses' => 'ContactsController@offer', 'as' => 'admin.contacts.offer']);
    Route::get('/offer/{id}/edit', ['uses' => 'ContactsController@edit', 'as' => 'admin.contacts.offer_edit']);
    Route::put('/offer/{id}', ['uses' => 'ContactsController@update', 'as' => 'admin.contacts.offer_update']);
	Route::resource('reqs', 'ReqController');
	Route::resource('contacts', 'ContactsController');
	Route::resource('questions', 'QuestionController');
	# Admin teams
	Route::get('/teams/{id}/switch_active', ['uses' => 'TeamController@switch_active', 'as' => 'admin.teams.switch_active']);
	Route::get('/teams/{id}/fav', ['uses' => 'TeamController@fav', 'as' => 'admin.teams.fav']);
	Route::post('/teams/reorder', ['uses' => 'TeamController@reorder', 'as' => 'admin.teams.reorder']);
	Route::resource('teams', 'TeamController');
	# Admin events
	Route::get('/sport-events/{id}/switch_active', ['uses' => 'SportEventController@switch_active', 'as' => 'admin.sport-events.switch_active']);
	Route::resource('sport-events', 'SportEventController');
	# Admin catalogs
	Route::resource('catalogs', 'CatalogController');
	Route::resource('catalogs.items', 'CatalogItemController');
	# Admin rules
	Route::resource('rules', 'RuleController');

	Route::resource('paytypes', 'PayTypeController');
	Route::resource('reqtypes', 'ReqTypeController');
	Route::resource('manuals', 'ManualController');

	Route::get('/subscribes', ['uses' => 'SubscribeController@index', 'as' => 'admin.subsribe.index']);
});
Route::group([
	'prefix' => 'api/v1',
	'namespace' => 'Api\V1',
], function () {
	Route::get('/faq/get', ['uses' => 'FaqController@get']);
	Route::get('/req/get', ['uses' => 'ReqController@get']);
	Route::get('/req/get_regions', ['uses' => 'ReqController@get_regions']);
	Route::get('/req/get_areas', ['uses' => 'ReqController@get_areas']);
	Route::get('/req/get_places', ['uses' => 'ReqController@get_places']);
	Route::get('/req/get_type_st', ['uses' => 'ReqController@get_type_st']);
	Route::post('/req/new_request', ['uses' => 'ReqController@new_request']);
	Route::get('/req/get_price', ['uses' => 'ReqController@get_price']);
	Route::get('/req/get_types', ['uses' => 'ReqController@get_types']);
	Route::post('/question/send', ['uses' => 'QuestionController@send']);
	Route::get('/contacts/get', ['uses' => 'ContactsController@get']);
	Route::get('/contacts/offer', ['uses' => 'ContactsController@offer']);
});


# Logout to redirect login page
Route::get('/logout', function () {
	Auth::logout();
	Session::flush();
	return Redirect::to('/auth/login');
})->before('auth.basic');


Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);


Route::get('/', function () {
	View::share('staticversion', Config::get('static.version'));
    $contact = Contacts::where('id', 1)->first();

	return view('welcome', compact('contact'));
});

Route::get('/offer', ['uses' => 'WelcomeController@offer']);
Route::get('/faq', ['uses' => 'WelcomeController@faq']);

Route::get('/admin/', [
	'middleware' => ['auth', 'roles'],
	'roles' => ['administrator', 'manager'],
	'uses' => 'Admin\ReqController@index'
]);

app/Models/Offer.php
<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Offer extends Model {

    protected $fillable = [
        'text',
        'name',
    ];

    public static $rules = array(
        'name' => 'required',
    );

    public static function rules($id = null)
    {
        $rules = self::$rules;

        if ($id) {
            foreach ($rules as &$rule) {
                $rule = str_replace(':id', $id, $rule);
            }
        }
        return $rules;
    }

    /**
     * @return array
     */
    function jsonSerialize()
    {
        return [
            'id' => (string) $this->id,
            'name' => $this->name,
            'text' =>  $this->name . ' ' . $this->text
        ];
    }
}

app/Http/Controllers/Admin/OfferController.php
<?php namespace App\Http\Controllers\Admin;

use App\Http\Controllers\AdminController;
use App\Http\Requests;
use App\Models\Bar;
use App\Models\Offer;
use Illuminate\Support\Facades\Response;
use Validator;

class OfferController extends AdminController
{

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $offers = Offer::all();
        return view('admin.bars.index', compact('offers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param Bar $bar
     * @return Response
     */
    public function create($bar)
    {
        return view('admin.offers.create', compact('bar'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Bar $bar
     * @return Response
     */
    public function store($bar)
    {
        $bar = Bar::find($bar);
        if ($bar) {
            $input = $this->request->all();

            $validator = Validator::make($input, Offer::$rules);
            if ($validator->fails()) {
                return redirect()->route('admin.bars.offers.create', [$bar->id])
                    ->withErrors($validator)
                    ->withInput();
            }
            $item = Offer::create($input);
            $bar->offers()->save($item);
        }

        return redirect()->route('admin.bars.edit', [$bar->id, '#offers']);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Bar $bar
     * @param  int $id
     * @return Response
     */
    public function edit($bar, $id)
    {
        $bar = Bar::find($bar);
        if ($bar) {
            $model = Offer::find($id);
            if ($model === null) {
                return redirect()->route('admin.bars.edit', [$bar->id, '#offers']);
            }
        }

        return view('admin.offers.edit', compact('model', 'bar'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Bar $bar
     * @param  int $id
     * @return Response
     */
    public function update($bar, $id)
    {
        $bar = Bar::find($bar);
        if ($bar) {
            $input = $this->request->all();

            $validator = Validator::make($input, Offer::rules($id));
            if ($validator->fails()) {
                return redirect()->route('admin.bars.offers.edit', [$bar->id, $id])
                    ->withErrors($validator)
                    ->withInput();
            }

            $model = Offer::find($id);
            $model->update($input);
        }
        return redirect()->route('admin.bars.edit', [$bar->id, '#offers']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Bar $bar
     * @param  int $id
     * @return Response
     */
    public function destroy($bar, $id)
    {
        Offer::find($id)->delete();
        return response()->json();
    }

}

resources/views/admin/offers/_form.blade.php
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@if (isset($model))
    {!! Form::model($model,['method' => 'PATCH', 'files' => true, 'route'=>['admin.bars.offers.update', $bar, $model->id], 'class' => 'form-horizontal']) !!}
@else
    {!! Form::open(['method' => 'POST', 'files' => true, 'route'=>['admin.bars.offers.index', $bar], 'class' => 'form-horizontal']) !!}
@endif

<div class="form-group">
    {!! Form::label('name', 'Название:', ['class' => 'control-label']) !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('text', 'Описание оффера:', ['class' => 'control-label']) !!}
    {!! Form::textarea('text', null, ['class' => 'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::submit(isset($model) ? 'Обновить' : 'Создать', ['class' => 'btn btn-default']) !!}
    {!! HTML::linkRoute('admin.bars.edit', 'Отмена', [$bar, '#offers'], array('class' => 'btn btn-default')) !!}
</div>

{!! Form::close() !!}

resources/views/admin/offers/create.blade.php
@extends('admin.layouts.default')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <p id="notice"></p>
            <h1>Добавить оффер</h1>
            <hr>
        </div>

        <div class="col-md-8">
            @include('admin.offers._form')
        </div>

    </div>
@stop

resources/views/admin/offers/edit.blade.php
@extends('admin.layouts.default')

@section('content')

    <div class="row">

        <div class="col-lg-12">
            <p id="notice"></p>
            <h1>Редактировать оффер</h1>
            <hr>
        </div>

        <div class="col-md-8">
            @include('admin.offers._form')
        </div>

    </div>

@stop

resources/views/admin/offers/index.blade.php
<div class="page-header">
    <h3>Офферы</h3>
    @if(!$offers->count())
        <em class="bg-warning">Ни одного оффера еще не добавлено. Нажмите кнопку "Добавить", чтобы исправить это.</em>
    @endif
</div>

<div class="row">
    <div class="col-xs-8">
        {!! HTML::linkRoute('admin.bars.offers.create', 'Добавить', [$bar->id], ['class' => 'btn btn-md btn-success']) !!}
    </div>
</div>

<table id="table" class="table table-striped table-hover">
    <thead>
    <tr>
        <th>Действия</th>
        <th>Название</th>
    </tr>
    </thead>
    <tbody>
    @foreach ($offers as $offer)
        <tr>
            <td>
                <div class="btn-group btn-group-xs" role="group">
                    <a href="{!!  URL::route('admin.bars.offers.edit', [$bar->id, $offer->id]) !!}" class="btn btn-warning"
                       title="Редактировать">
                        <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
                    </a>
                    <a href="{!!  URL::route('admin.bars.offers.destroy', [$bar->id, $offer->id]) !!}"
                       class="btn btn-danger deleteObject" title="Удалить">
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                    </a>
                </div>
            </td>
            <td>
                {{ $offer->name }}
            </td>
        </tr>
    @endforeach

    </tbody>
</table>

resources/views/admin/offers/show.blade.php
@extends('admin.layouts.default')

{{-- Web site Title --}}
@section('title') Бары @parent @stop

{{-- Content --}}
@section('content')
    <div class="page-header">
        <h3>{{ $item->name }}</h3>
    </div>

    <div class="row">
        <div class="col-xs-8">
            {!! HTML::linkRoute('admin.catalogs.items.create', 'Добавить', [], ['class' => 'btn btn-md btn-success']) !!}
        </div>
    </div>

    <table id="table" class="table table-striped table-hover">
        <thead>
        <tr>
            <th>Название</th>
            <th>Действия</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($items as $item)
            <tr>
                <td>
                    <a href="{!!  URL::route('admin.catalogs.items.show', [$item->id]) !!}">
                        {{ $item->name }}
                    </a>
                </td>
                <td>
                    <div class="btn-group btn-group-xs" role="group">
                        <a href="{!!  URL::route('admin.catalogs.items.edit', [$item->id]) !!}" class="btn btn-warning"
                           title="Редактировать">
                            <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
                        </a>
                        <a href="{!!  URL::route('admin.catalogs.items.destroy', [$item->id]) !!}"
                           class="btn btn-danger deleteObject" title="Удалить">
                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                        </a>
                    </div>
                </td>
            </tr>
        @endforeach

        </tbody>
    </table>
@stop