app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

use App\Models\Contacts;

Route::group([
	'prefix' => 'admin',
	'namespace' => 'Admin',
	'middleware' => ['auth', 'roles'],
	'roles' => ['administrator', 'manager'],
], function () {
	# Admin users
	Route::resource('users', 'UserController');
	Route::resource('settings', 'SettingController');
	# Admin bars
	Route::get('/faqs/{id}/switchActive', ['uses' => 'FaqController@switchActive', 'as' => 'admin.faqs.switchActive']);
	Route::resource('faqs', 'FaqController');
	Route::get('/reqs/statistic', ['uses' => 'ReqController@statistic', 'as' => 'admin.reqs.statistic']);
	Route::get('/reqs/change_month', ['uses' => 'ReqController@change_month', 'as' => 'admin.reqs.change_month']);
	Route::get('/reqs/excel', ['uses' => 'ReqController@excel', 'as' => 'admin.reqs.excel']);
	Route::get('/reqs/search', ['uses' => 'ReqController@search', 'as' => 'admin.reqs.search']);
	Route::get('/reqs/switch_status/{id}/{status}', ['uses' => 'ReqController@switch_status', 'as' => 'admin.reqs.switch_status']);
	Route::post('/reqs/load_file/{id}', ['uses' => 'ReqController@load_file', 'as' => 'admin.reqs.load_file']);
	Route::get('/reqs/{id}/first', ['uses' => 'ReqController@first', 'as' => 'admin.reqs.first']);
	Route::get('/reqs/{id}/update_watch', ['uses' => 'ReqController@update_watch', 'as' => 'admin.reqs.update_watch']);
	Route::get('/contacts/offer', ['uses' => 'ContactsController@offer', 'as' => 'admin.contacts.offer']);
    Route::get('/offer/{id}/edit', ['uses' => 'ContactsController@edit', 'as' => 'admin.contacts.offer_edit']);
    Route::put('/offer/{id}', ['uses' => 'ContactsController@update', 'as' => 'admin.contacts.offer_update']);
	Route::resource('reqs', 'ReqController');
	Route::resource('contacts', 'ContactsController');
	Route::resource('questions', 'QuestionController');
	# Admin teams
	Route::get('/teams/{id}/switch_active', ['uses' => 'TeamController@switch_active', 'as' => 'admin.teams.switch_active']);
	Route::get('/teams/{id}/fav', ['uses' => 'TeamController@fav', 'as' => 'admin.teams.fav']);
	Route::post('/teams/reorder', ['uses' => 'TeamController@reorder', 'as' => 'admin.teams.reorder']);
	Route::resource('teams', 'TeamController');
	# Admin events
	Route::get('/sport-events/{id}/switch_active', ['uses' => 'SportEventController@switch_active', 'as' => 'admin.sport-events.switch_active']);
	Route::resource('sport-events', 'SportEventController');
	# Admin catalogs
	Route::resource('catalogs', 'CatalogController');
	Route::resource('catalogs.items', 'CatalogItemController');
	# Admin rules
	Route::resource('rules', 'RuleController');

	Route::resource('paytypes', 'PayTypeController');
	Route::resource('reqtypes', 'ReqTypeController');
	Route::resource('manuals', 'ManualController');

	Route::get('/subscribes', ['uses' => 'SubscribeController@index', 'as' => 'admin.subsribe.index']);
});
Route::group([
	'prefix' => 'api/v1',
	'namespace' => 'Api\V1',
], function () {
	Route::get('/faq/get', ['uses' => 'FaqController@get']);
	Route::get('/req/get', ['uses' => 'ReqController@get']);
	Route::get('/req/get_regions', ['uses' => 'ReqController@get_regions']);
	Route::get('/req/get_areas', ['uses' => 'ReqController@get_areas']);
	Route::get('/req/get_places', ['uses' => 'ReqController@get_places']);
	Route::get('/req/get_type_st', ['uses' => 'ReqController@get_type_st']);
	Route::post('/req/new_request', ['uses' => 'ReqController@new_request']);
	Route::get('/req/get_price', ['uses' => 'ReqController@get_price']);
	Route::get('/req/get_types', ['uses' => 'ReqController@get_types']);
	Route::post('/question/send', ['uses' => 'QuestionController@send']);
	Route::get('/contacts/get', ['uses' => 'ContactsController@get']);
	Route::get('/contacts/offer', ['uses' => 'ContactsController@offer']);
});


# Logout to redirect login page
Route::get('/logout', function () {
	Auth::logout();
	Session::flush();
	return Redirect::to('/auth/login');
})->before('auth.basic');


Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);


Route::get('/', function () {
	View::share('staticversion', Config::get('static.version'));
    $contact = Contacts::where('id', 1)->first();

	return view('welcome', compact('contact'));
});

Route::get('/offer', ['uses' => 'WelcomeController@offer']);
Route::get('/faq', ['uses' => 'WelcomeController@faq']);

Route::get('/admin/', [
	'middleware' => ['auth', 'roles'],
	'roles' => ['administrator', 'manager'],
	'uses' => 'Admin\ReqController@index'
]);

app/Models/Catalog.php
<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Catalog extends Model {

    protected $fillable = [
        'name',
    ];

    public static $rules = [
        'name' => 'required',
    ];

    /**
     * Get the items for the catalog.
     */
    public function items()
    {
        return $this->hasMany('App\Models\CatalogItem');
    }

    public static function rules($id = null)
    {
        $rules = self::$rules;

        if ($id) {
            foreach ($rules as &$rule) {
                $rule = str_replace(':id', $id, $rule);
            }
        }
        return $rules;
    }

    public function getListForDropdown($emptyItem = false)
    {
        $items = $this->items->lists('name', 'id');
        $stations = [];
        if ($emptyItem) {
            $stations[''] = $emptyItem;
        }
        foreach ($items as $key => $item) {
            $stations[$key] = $item;
        }
        return $stations;
    }
}

app/Http/Controllers/Admin/CatalogController.php
<?php namespace App\Http\Controllers\Admin;

use App\Http\Controllers\AdminController;
use App\Http\Requests;
use App\Models\Catalog;
use Illuminate\Support\Facades\Response;
use Validator;

class CatalogController extends AdminController
{


    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $catalogs = Catalog::all();
        return view('admin.catalogs.index', compact('catalogs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('admin.catalogs.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store()
    {
        $input = $this->request->all();

        $validator = Validator::make($input, Catalog::$rules);
        if ($validator->fails()) {
            return redirect()->route('admin.catalogs.create')
                ->withErrors($validator)
                ->withInput();
        }

        Catalog::create($input);

        return redirect()->route('admin.catalogs.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        $model = Catalog::find($id);
        return view('admin.catalogs.show', compact('model'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        $model = Catalog::find($id);
        if($model === null){
            return redirect('admin/catalogs');
        }
        return view('admin.catalogs.edit', compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int $id
     * @return Response
     */
    public function update($id)
    {
        $input = $this->request->all();

        $validator = Validator::make($input, Catalog::rules($id));
        if ($validator->fails()) {
            return redirect()->route('admin.catalogs.edit', ['id' => $id])
                ->withErrors($validator)
                ->withInput();
        }

        $model = Catalog::find($id);
        $model->update($input);
        return redirect('admin/catalogs');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {
        Catalog::find($id)->delete();
        return response()->json();
    }

}

resources/views/admin/catalogs/_form.blade.php
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@if (isset($model))
    {!! Form::model($model,['method' => 'PATCH', 'files' => true, 'route'=>['admin.catalogs.update', $model->id], 'class' => 'form-horizontal']) !!}
@else
    {!! Form::open(['method' => 'POST', 'files' => true, 'route'=>['admin.catalogs.index'], 'class' => 'form-horizontal']) !!}
@endif

<div class="form-group">
    {!! Form::label('name', 'Название:', ['class' => 'control-label']) !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::submit(isset($model) ? 'Обновить' : 'Создать', ['class' => 'btn btn-default']) !!}
    {!! HTML::linkRoute('admin.catalogs.index', 'Отмена', [], array('class' => 'btn btn-default')) !!}
</div>

{!! Form::close() !!}

resources/views/admin/catalogs/create.blade.php
@extends('admin.layouts.default')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <p id="notice"></p>
            <h1>Добавить справочник</h1>
            <hr>
        </div>

        <div class="col-md-8">
            @include('admin.catalogs._form')
        </div>

    </div>
@stop

resources/views/admin/catalogs/edit.blade.php
@extends('admin.layouts.default')

@section('content')

    <div class="row">

        <div class="col-lg-12">
            <p id="notice"></p>
            <h1>Редактировать справочник</h1>
            <hr>
        </div>

        <div class="col-md-8">
            @include('admin.catalogs._form')
        </div>

    </div>

@stop

resources/views/admin/catalogs/index.blade.php
@extends('admin.layouts.default')

{{-- Web site Title --}}
@section('title') Бары @parent @stop

{{-- Content --}}
@section('content')
    <div class="page-header">
        <h3>Справочники</h3>
        @if(!$catalogs->count())
            <em class="bg-warning">Ни одного справочника еще не добавлено. Нажмите кнопку "Добавить", чтобы исправить это.</em>
        @endif
    </div>

    <div class="row">
        <div class="col-xs-8">
            {!! HTML::linkRoute('admin.catalogs.create', 'Добавить', [], ['class' => 'btn btn-md btn-success']) !!}
        </div>
    </div>

    <table id="table" class="table table-striped table-hover">
        <thead>
        <tr>
            <th>Действия</th>
            <th>Название</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($catalogs as $catalog)
            <tr>
                <td>
                    <div class="btn-group btn-group-xs" role="group">
                        <a href="{!!  URL::route('admin.catalogs.edit', [$catalog->id]) !!}" class="btn btn-warning"
                           title="Редактировать">
                            <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
                        </a>
                        <a href="{!!  URL::route('admin.catalogs.destroy', [$catalog->id]) !!}"
                           class="btn btn-danger deleteObject" title="Удалить">
                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                        </a>
                    </div>
                </td>
                <td>
                    <a href="{!!  URL::route('admin.catalogs.show', [$catalog->id]) !!}">
                        {{ $catalog->name }}
                    </a>
                </td>
            </tr>
        @endforeach

        </tbody>
    </table>
@stop

resources/views/admin/catalogs/show.blade.php
@extends('admin.layouts.default')

{{-- Web site Title --}}
@section('title') Бары @parent @stop

{{-- Content --}}
@section('content')
    <div class="page-header">
        <h3>{{ $model->name }}</h3>
    </div>

    <div class="row">
        <div class="col-xs-8">
            {!! HTML::linkRoute('admin.catalogs.items.create', 'Добавить', [$model->id], ['class' => 'btn btn-md btn-success']) !!}
        </div>
    </div>
    <table id="table" class="table table-striped table-hover">
        <thead>
        <tr>
            <th>Действия</th>
            <th>Название</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($model->items as $item)
            <tr>
                <td>
                    <div class="btn-group btn-group-xs" role="group">
                        <a href="{!!  URL::route('admin.catalogs.items.edit', [$model->id, $item->id]) !!}" class="btn btn-warning"
                           title="Редактировать">
                            <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
                        </a>
                        <a href="{!!  URL::route('admin.catalogs.items.destroy', [$model->id, $item->id]) !!}"
                           class="btn btn-danger deleteObject" title="Удалить">
                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                        </a>
                    </div>
                </td>
                <td>
                    @if($item->img)
                        <img height="20" src="{{ $item->getImg() }}" />
                    @endif
                    {{ $item->name }}
                </td>
            </tr>
        @endforeach

        </tbody>
    </table>
@stop