app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

use App\Models\Contacts;

Route::group([
	'prefix' => 'admin',
	'namespace' => 'Admin',
	'middleware' => ['auth', 'roles'],
	'roles' => ['administrator', 'manager'],
], function () {
	# Admin users
	Route::resource('users', 'UserController');
	Route::resource('settings', 'SettingController');
	# Admin bars
	Route::get('/faqs/{id}/switchActive', ['uses' => 'FaqController@switchActive', 'as' => 'admin.faqs.switchActive']);
	Route::resource('faqs', 'FaqController');
	Route::get('/reqs/statistic', ['uses' => 'ReqController@statistic', 'as' => 'admin.reqs.statistic']);
	Route::get('/reqs/change_month', ['uses' => 'ReqController@change_month', 'as' => 'admin.reqs.change_month']);
	Route::get('/reqs/excel', ['uses' => 'ReqController@excel', 'as' => 'admin.reqs.excel']);
	Route::get('/reqs/search', ['uses' => 'ReqController@search', 'as' => 'admin.reqs.search']);
	Route::get('/reqs/switch_status/{id}/{status}', ['uses' => 'ReqController@switch_status', 'as' => 'admin.reqs.switch_status']);
	Route::post('/reqs/load_file/{id}', ['uses' => 'ReqController@load_file', 'as' => 'admin.reqs.load_file']);
	Route::get('/reqs/{id}/first', ['uses' => 'ReqController@first', 'as' => 'admin.reqs.first']);
	Route::get('/reqs/{id}/update_watch', ['uses' => 'ReqController@update_watch', 'as' => 'admin.reqs.update_watch']);
	Route::get('/contacts/offer', ['uses' => 'ContactsController@offer', 'as' => 'admin.contacts.offer']);
    Route::get('/offer/{id}/edit', ['uses' => 'ContactsController@edit', 'as' => 'admin.contacts.offer_edit']);
    Route::put('/offer/{id}', ['uses' => 'ContactsController@update', 'as' => 'admin.contacts.offer_update']);
	Route::resource('reqs', 'ReqController');
	Route::resource('contacts', 'ContactsController');
	Route::resource('questions', 'QuestionController');
	# Admin teams
	Route::get('/teams/{id}/switch_active', ['uses' => 'TeamController@switch_active', 'as' => 'admin.teams.switch_active']);
	Route::get('/teams/{id}/fav', ['uses' => 'TeamController@fav', 'as' => 'admin.teams.fav']);
	Route::post('/teams/reorder', ['uses' => 'TeamController@reorder', 'as' => 'admin.teams.reorder']);
	Route::resource('teams', 'TeamController');
	# Admin events
	Route::get('/sport-events/{id}/switch_active', ['uses' => 'SportEventController@switch_active', 'as' => 'admin.sport-events.switch_active']);
	Route::resource('sport-events', 'SportEventController');
	# Admin catalogs
	Route::resource('catalogs', 'CatalogController');
	Route::resource('catalogs.items', 'CatalogItemController');
	# Admin rules
	Route::resource('rules', 'RuleController');

	Route::resource('paytypes', 'PayTypeController');
	Route::resource('reqtypes', 'ReqTypeController');
	Route::resource('manuals', 'ManualController');

	Route::get('/subscribes', ['uses' => 'SubscribeController@index', 'as' => 'admin.subsribe.index']);
});
Route::group([
	'prefix' => 'api/v1',
	'namespace' => 'Api\V1',
], function () {
	Route::get('/faq/get', ['uses' => 'FaqController@get']);
	Route::get('/req/get', ['uses' => 'ReqController@get']);
	Route::get('/req/get_regions', ['uses' => 'ReqController@get_regions']);
	Route::get('/req/get_areas', ['uses' => 'ReqController@get_areas']);
	Route::get('/req/get_places', ['uses' => 'ReqController@get_places']);
	Route::get('/req/get_type_st', ['uses' => 'ReqController@get_type_st']);
	Route::post('/req/new_request', ['uses' => 'ReqController@new_request']);
	Route::get('/req/get_price', ['uses' => 'ReqController@get_price']);
	Route::get('/req/get_types', ['uses' => 'ReqController@get_types']);
	Route::post('/question/send', ['uses' => 'QuestionController@send']);
	Route::get('/contacts/get', ['uses' => 'ContactsController@get']);
	Route::get('/contacts/offer', ['uses' => 'ContactsController@offer']);
});


# Logout to redirect login page
Route::get('/logout', function () {
	Auth::logout();
	Session::flush();
	return Redirect::to('/auth/login');
})->before('auth.basic');


Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);


Route::get('/', function () {
	View::share('staticversion', Config::get('static.version'));
    $contact = Contacts::where('id', 1)->first();

	return view('welcome', compact('contact'));
});

Route::get('/offer', ['uses' => 'WelcomeController@offer']);
Route::get('/faq', ['uses' => 'WelcomeController@faq']);

Route::get('/admin/', [
	'middleware' => ['auth', 'roles'],
	'roles' => ['administrator', 'manager'],
	'uses' => 'Admin\ReqController@index'
]);

app/Models/Team.php
<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Config;

class Team extends Model implements \JsonSerializable
{

    protected $fillable = [
        'name',
        'logo',
        'active',
        'fav',
        'sort',
    ];

    public static $rules = array(
        'name' => 'required',
    );

    const MAX_TEAMS = 6;

    public static function rules($id = null)
    {
        $rules = self::$rules;

        if ($id) {
            foreach ($rules as &$rule) {
                $rule = str_replace(':id', $id, $rule);
            }
        }
        return $rules;
    }

    public function save(array $options = array())
    {
        if (Input::hasFile('logo')) {

            $file = Input::file('logo');
            $fpath = base_path() . '/public/static/img/teams/';

            $filename = $file->getClientOriginalName();
            $extension = $file->getClientOriginalExtension();
            $fname = sha1($filename . time()) . '.' . $extension;

            $file->move($fpath, $fname);
            $this->logo = '/img/teams/' . $fname;
        }

        parent::save($options);
    }

    /**
     * @return array
     */
    function jsonSerialize()
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'logo' => $this->getLogo(),
        ];
    }

    public static function getMaxTeams()
    {
        return self::MAX_TEAMS;
    }

    public function getLogo()
    {
        return $this->logo ? Config::get('app.url') . $this->logo : Config::get('app.url') . '/img/logo.png';
    }
}

app/Http/Controllers/Admin/TeamController.php
<?php namespace App\Http\Controllers\Admin;

use App\Http\Controllers\AdminController;
use App\Http\Requests;
use App\Models\Team;
use Illuminate\Support\Facades\Response;
use Validator;

class TeamController extends AdminController
{


    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $teams = Team::orderBy('fav', 'desc')->orderBy('sort', 'asc')->orderBy('name', 'asc')->get();
        return view('admin.teams.index', compact('teams'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('admin.teams.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store()
    {
        $input = $this->request->all();

        $validator = Validator::make($input, Team::$rules);
        if ($validator->fails()) {
            return redirect()->route('admin.teams.create')
                ->withErrors($validator)
                ->withInput();
        }

        Team::create($input);

        return redirect()->route('admin.teams.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        $model = Team::find($id);
        return view('admin.teams.show', compact('model'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        $model = Team::find($id);
        if($model === null){
            return redirect('admin/teams');
        }
        return view('admin.teams.edit', compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int $id
     * @return Response
     */
    public function update($id)
    {
        $input = $this->request->all();

        $validator = Validator::make($input, Team::rules($id));
        if ($validator->fails()) {
            return redirect()->route('admin.teams.edit', ['id' => $id])
                ->withErrors($validator)
                ->withInput();
        }

        $model = Team::find($id);
        $model->update($input);
        return redirect('admin/teams');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {
        Team::find($id)->delete();
        return response()->json();
    }

    public function switch_active($id)
    {
        $team = Team::find($id);
        if($team === null){
            return redirect('admin/teams');
        }
        $team->active = !$team->active;
        $team->save();
        return redirect('admin/teams');
    }

    public function fav($id)
    {
        $team = Team::find($id);
        if($team === null){
            return redirect('admin/teams');
        }
        $team->fav = !$team->fav;
        $team->save();
        return redirect('admin/teams');
    }

    public function reorder()
    {
        $items = $this->request->all()['items'];
        foreach ($items as $k => $v) {
            Team::where('id', $v)->update(['sort' => $k]);
        }
    }

}

app/Http/Controllers/Api/V1/TeamController.php
<?php namespace App\Http\Controllers\Api\V1;

use App\Http\Requests;
use App\Models\Team;
use Illuminate\Support\Facades\Response;
use Illuminate\Routing\Controller as BaseController;
use Validator;
use JWTAuth;

class TeamController extends BaseController
{

    public function all()
    {
        $teams = Team::where('active', true)->orderBy('fav', 'desc')->orderBy('sort', 'asc')->orderBy('name', 'asc')->get();
        $result = [];
        foreach ($teams as $team) {
            $result[] = $team;
        }
        return response()->json(['teams' => $result], 200);
    }

    public function postFavorite($id)
    {
        if (! $token = JWTAuth::parseToken()) {
            return $this->response->errorUnauthorized();
        }
        $user = JWTAuth::parseToken()->authenticate();
        $team = Team::find($id);
        $team !== NULL or abort(404, 'Team with id #' . $id . ' - not found');
        //проверка на уже фаворита
        $user->addFavoriteTeam($team);
        return response()->json([], 201);
    }

    public function deleteFavorite($id)
    {
        if (! $token = JWTAuth::parseToken()) {
            return $this->response->errorUnauthorized();
        }
        $user = JWTAuth::parseToken()->authenticate();
        $team = Team::find($id);
        $team !== NULL or abort(404, 'Team with id #' . $id . ' - not found');
        $user->removeFavoriteTeam($id);
        return response()->json([], 204);
    }

}

resources/views/admin/teams/_form.blade.php
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<hr>

@if (isset($model))
    {!! Form::model($model,['method' => 'PATCH', 'files' => true, 'route'=>['admin.teams.update', $model->id], 'class' => 'form-horizontal']) !!}
@else
    {!! Form::open(['method' => 'POST', 'files' => true, 'route'=>['admin.teams.index'], 'class' => 'form-horizontal']) !!}
@endif

<div class="form-group">
    {!! Form::label('name', 'Название:', ['class' => 'control-label']) !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>
@if (isset($model))
    <div class="form-group">
        <img class="admin-img" src="{{$model->logo}}"/>
    </div>
@endif
<div class="form-group">
    {!! Form::label('logo', 'Лого:', ['class' => 'control-label']) !!}
    {!! Form::file('logo', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::submit(isset($model) ? 'Обновить' : 'Создать', ['class' => 'btn btn-default']) !!}
    {!! HTML::linkRoute('admin.teams.index', 'Отмена', [], array('class' => 'btn btn-default')) !!}
</div>

{!! Form::close() !!}

resources/views/admin/teams/create.blade.php
@extends('admin.layouts.default')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <p id="notice"></p>
            <h1>Добавить команду</h1>
            <hr>
        </div>

        <div class="col-md-8">
            @include('admin.teams._form')
        </div>

    </div>
@stop

resources/views/admin/teams/edit.blade.php
@extends('admin.layouts.default')

@section('content')

    <div class="row">

        <div class="col-lg-12">
            <p id="notice"></p>
            <h1>Редактировать команду</h1>
            <hr>
        </div>

        <div class="col-md-8">
            @include('admin.teams._form')
        </div>

    </div>

@stop

resources/views/admin/teams/index.blade.php
@extends('admin.layouts.default')

{{-- Web site Title --}}
@section('title') Команды @parent @stop

{{-- Content --}}
@section('content')
    <div class="page-header">
        <h3>Команды</h3>
        @if(!$teams->count())
            <em class="bg-warning">Ни одной команды еще не добавлено. Нажмите кнопку "Добавить", чтобы исправить это.</em>
        @endif
    </div>

    <div class="row">
        <div class="col-xs-8">
            {!! HTML::linkRoute('admin.teams.create', 'Добавить', [], ['class' => 'btn btn-md btn-success']) !!}
        </div>
    </div>

    <table id="table" class="table table-striped table-hover">
        <thead>
        <tr>
            <th>Действия</th>
            <th>Логотип</th>
            <th>Название</th>
        </tr>
        </thead>
        <tbody id="sortable">
        @foreach ($teams as $team)
            <tr data-team_id="{{ $team->id }}">
                <td>
                    <div class="btn-group btn-group-xs" role="group">
                        <a href="{!!  URL::route('admin.teams.edit', [$team->id]) !!}" class="btn btn-warning"
                           title="Редактировать">
                            <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
                        </a>
                        <a href="{!!  URL::route('admin.teams.destroy', [$team->id]) !!}"
                           class="btn btn-danger deleteObject" title="Удалить">
                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                        </a>
                        <a href="{!!  URL::route('admin.teams.switch_active', [$team->id]) !!}"
                           class="btn {!! $team->active ? 'btn-primary' : 'btn-default' !!}" title="{!! $team->active ? 'Не показывать' : 'Активировать' !!}">
                            <span class="glyphicon {!! $team->active ? 'glyphicon-eye-open' : 'glyphicon-eye-close' !!}" aria-hidden="true"></span>
                        </a>
                        <a href="{!!  URL::route('admin.teams.fav', [$team->id]) !!}"
                           class="btn {!! $team->fav ? 'btn-success' : 'btn-default' !!}" title="{!! $team->fav ? 'Обычная' : 'Выбор редакции' !!}">
                            <span class="glyphicon {!! $team->fav ? 'glyphicon-star' : 'glyphicon-star-empty' !!}" aria-hidden="true"></span>
                        </a>
                        <div class="btn btn-default sort-handler ui-sortable-handle">
                            <i class="glyphicon glyphicon-resize-vertical"></i>
                        </div>
                    </div>
                </td>
                <td><img height="40" src="{{ $team->getLogo() }}" /></td>
                <td>{{ $team->name }}</td>
            </tr>
        @endforeach

        </tbody>
    </table>
@stop