app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

use App\Models\Contacts;

Route::group([
	'prefix' => 'admin',
	'namespace' => 'Admin',
	'middleware' => ['auth', 'roles'],
	'roles' => ['administrator', 'manager'],
], function () {
	# Admin users
	Route::resource('users', 'UserController');
	Route::resource('settings', 'SettingController');
	# Admin bars
	Route::get('/faqs/{id}/switchActive', ['uses' => 'FaqController@switchActive', 'as' => 'admin.faqs.switchActive']);
	Route::resource('faqs', 'FaqController');
	Route::get('/reqs/statistic', ['uses' => 'ReqController@statistic', 'as' => 'admin.reqs.statistic']);
	Route::get('/reqs/change_month', ['uses' => 'ReqController@change_month', 'as' => 'admin.reqs.change_month']);
	Route::get('/reqs/excel', ['uses' => 'ReqController@excel', 'as' => 'admin.reqs.excel']);
	Route::get('/reqs/search', ['uses' => 'ReqController@search', 'as' => 'admin.reqs.search']);
	Route::get('/reqs/switch_status/{id}/{status}', ['uses' => 'ReqController@switch_status', 'as' => 'admin.reqs.switch_status']);
	Route::post('/reqs/load_file/{id}', ['uses' => 'ReqController@load_file', 'as' => 'admin.reqs.load_file']);
	Route::get('/reqs/{id}/first', ['uses' => 'ReqController@first', 'as' => 'admin.reqs.first']);
	Route::get('/reqs/{id}/update_watch', ['uses' => 'ReqController@update_watch', 'as' => 'admin.reqs.update_watch']);
	Route::get('/contacts/offer', ['uses' => 'ContactsController@offer', 'as' => 'admin.contacts.offer']);
    Route::get('/offer/{id}/edit', ['uses' => 'ContactsController@edit', 'as' => 'admin.contacts.offer_edit']);
    Route::put('/offer/{id}', ['uses' => 'ContactsController@update', 'as' => 'admin.contacts.offer_update']);
	Route::resource('reqs', 'ReqController');
	Route::resource('contacts', 'ContactsController');
	Route::resource('questions', 'QuestionController');
	# Admin teams
	Route::get('/teams/{id}/switch_active', ['uses' => 'TeamController@switch_active', 'as' => 'admin.teams.switch_active']);
	Route::get('/teams/{id}/fav', ['uses' => 'TeamController@fav', 'as' => 'admin.teams.fav']);
	Route::post('/teams/reorder', ['uses' => 'TeamController@reorder', 'as' => 'admin.teams.reorder']);
	Route::resource('teams', 'TeamController');
	# Admin events
	Route::get('/sport-events/{id}/switch_active', ['uses' => 'SportEventController@switch_active', 'as' => 'admin.sport-events.switch_active']);
	Route::resource('sport-events', 'SportEventController');
	# Admin catalogs
	Route::resource('catalogs', 'CatalogController');
	Route::resource('catalogs.items', 'CatalogItemController');
	# Admin rules
	Route::resource('rules', 'RuleController');

	Route::resource('paytypes', 'PayTypeController');
	Route::resource('reqtypes', 'ReqTypeController');
	Route::resource('manuals', 'ManualController');

	Route::get('/subscribes', ['uses' => 'SubscribeController@index', 'as' => 'admin.subsribe.index']);
});
Route::group([
	'prefix' => 'api/v1',
	'namespace' => 'Api\V1',
], function () {
	Route::get('/faq/get', ['uses' => 'FaqController@get']);
	Route::get('/req/get', ['uses' => 'ReqController@get']);
	Route::get('/req/get_regions', ['uses' => 'ReqController@get_regions']);
	Route::get('/req/get_areas', ['uses' => 'ReqController@get_areas']);
	Route::get('/req/get_places', ['uses' => 'ReqController@get_places']);
	Route::get('/req/get_type_st', ['uses' => 'ReqController@get_type_st']);
	Route::post('/req/new_request', ['uses' => 'ReqController@new_request']);
	Route::get('/req/get_price', ['uses' => 'ReqController@get_price']);
	Route::get('/req/get_types', ['uses' => 'ReqController@get_types']);
	Route::post('/question/send', ['uses' => 'QuestionController@send']);
	Route::get('/contacts/get', ['uses' => 'ContactsController@get']);
	Route::get('/contacts/offer', ['uses' => 'ContactsController@offer']);
});


# Logout to redirect login page
Route::get('/logout', function () {
	Auth::logout();
	Session::flush();
	return Redirect::to('/auth/login');
})->before('auth.basic');


Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);


Route::get('/', function () {
	View::share('staticversion', Config::get('static.version'));
    $contact = Contacts::where('id', 1)->first();

	return view('welcome', compact('contact'));
});

Route::get('/offer', ['uses' => 'WelcomeController@offer']);
Route::get('/faq', ['uses' => 'WelcomeController@faq']);

Route::get('/admin/', [
	'middleware' => ['auth', 'roles'],
	'roles' => ['administrator', 'manager'],
	'uses' => 'Admin\ReqController@index'
]);

app/Http/Controllers/Admin/ReqTypeController.php
<?php namespace App\Http\Controllers\Admin;

use App\Http\Controllers\AdminController;
use App\Http\Requests;
use App\Models\Bar;
use App\Models\Catalog;
use App\Models\ReqType;
use App\Models\Setting;
use App\Models\SportEvent;
use Illuminate\Support\Facades\Response;
use Validator;

class ReqTypeController extends AdminController
{

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $types = ReqType::all();
        return view('admin.reqtypes.index', compact('types'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('admin.reqtypes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store()
    {
        $input = $this->request->all();

        $validator = Validator::make($input, ReqType::$rules);
        if ($validator->fails()) {
            return redirect()->route('admin.reqtypes.index')
                ->withErrors($validator)
                ->withInput();
        }

        ReqType::create($input);

        return redirect()->route('admin.reqtypes.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        $model = ReqType::find($id);
        return view('admin.reqtypes.show', compact('model'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        $model = ReqType::find($id);
        if($model === null){
            return redirect('admin/reqtypes');
        }
        return view('admin.reqtypes.edit', compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int $id
     * @return Response
     */
    public function update($id)
    {
        $input = $this->request->all();
        $validator = Validator::make($input, ReqType::$rules);
        if ($validator->fails()) {
            return response()->json(['errors' => 'Ошибка валидации']);
        }

        $model = ReqType::find($id);
        $model->update($input);
        return response()->json(['success' => true]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {
        Bar::find($id)->delete();
        return response()->json();
    }

}

resources/views/admin/reqtypes/_form.blade.php
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    <hr>
@endif
@if (isset($model))
    {!! Form::model($model,['method' => 'PATCH','route'=>['admin.reqtypes.update', $model->id], 'class' => 'form-horizontal']) !!}
@else
    {!! Form::open(['method' => 'POST', 'route'=>['admin.reqtypes.index'], 'class' => 'form-horizontal']) !!}
@endif


<div class="form-group">
    {!! Form::label('name', 'Название:', ['class' => 'control-label']) !!}
    {!! Form::text('name', null, ['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! HTML::linkRoute('admin.reqtypes.index', 'Отмена', [], ['class' => 'btn btn-default']) !!}
    {!! Form::submit(isset($model) ? 'Обновить' : 'Сохранить', ['class' => 'btn btn-default']) !!}
</div>

{!! Form::close() !!}

resources/views/admin/reqtypes/create.blade.php
@extends('admin.layouts.default')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <p id="notice"></p>
            <h1>Добавить тип заявки</h1>
            <hr>
        </div>

        <div class="col-md-8">
            @include('admin.reqtypes._form')
        </div>

    </div>
@stop

resources/views/admin/reqtypes/edit.blade.php
@extends('admin.layouts.default')

@section('content')

    <div class="row">

        <div class="col-lg-12">
            <p id="notice"></p>
            <h1>Редактировать тип заявки</h1>
            <hr>
        </div>

        <div class="col-md-8">
            @include('admin.reqtypes._form')
        </div>

    </div>

@stop

resources/views/admin/reqtypes/index.blade.php
@extends('admin.layouts.default')

{{-- Web site Title --}}
@section('title') Типы заявки @parent @stop

{{-- Content --}}
@section('content')
    <div class="page-header">
        <h3>Типы заявок</h3>
        <em class="bg-warning">Здесь отображены типы заявок.</em>
    </div>
    <div class="row">
        <div class="col-xs-8">
            {!! HTML::linkRoute('admin.reqtypes.create', 'Добавить', [], ['class' => 'btn btn-md btn-success']) !!}
        </div>
    </div>
    <table id="table" class="table table-striped table-hover">
        <thead>
        <tr>
            <th class="w10">Действия</th>
            <th>Название</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($types as $type)
            <tr>
                <td>
                    <div class="btn-group btn-group-xs" role="group">
                        <a href="{!!  URL::route('admin.reqtypes.edit', [$type->id]) !!}" class="btn btn-default" title="Редактировать">
                            <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
                        </a>
                        <a href="{!!  URL::route('admin.reqtypes.destroy', [$type->id]) !!}"
                           class="btn btn-default deleteObject" title="Удалить">
                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                        </a>
                    </div>
                </td>
                <td>{{ $type->name }}</td>
            </tr>
        @endforeach

        </tbody>
    </table>
@stop